version: '2'
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: cinema-nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"

  movies:
    build: ./movies
    image: stockallj/cinema-movies
    container_name: cinema-movies
    depends_on:
      - db
      - proxy
    links:
      - db
    environment:
      VIRTUAL_HOST: movies.dev
      DATABASE_HOST: db

  bookings:
    build: ./bookings
    image: stockallj/cinema-bookings
    container_name: cinema-bookings
    depends_on:
      - db
      - proxy
    links:
      - db
    environment:
      VIRTUAL_HOST: bookings.dev
      DATABASE_HOST: db

  showtimes:
    build: ./showtimes
    image: stockallj/cinema-showtimes
    container_name: cinema-showtimes
    depends_on:
      - db
      - proxy
    links:
      - db
    environment:
      VIRTUAL_HOST: showtimes.dev
      DATABASE_HOST: db

  users:
    build: ./users
    image: stockallj/cinema-users
    container_name: cinema-users
    depends_on:
      - db
      - proxy
    links:
      - db
    environment:
      VIRTUAL_HOST: users.dev
      DATABASE_HOST: db

  backup:
    build: ./backup
    image: stockallj/cinema-backup
    container_name: cinema-backup
    depends_on:
      - db
      - proxy
    links:
      - db
    volumes:
      - ./backup:/backup:rw
    environment:
      VIRTUAL_HOST: backup.dev
      DATABASE_HOST: db

  db:
    image: mongo:3.3
    container_name: cinema-db
    ports:
      - "27017:27017"
    extra_hosts:
     # The backup and restore scripts use as the hostname
    - "db:127.0.0.1"
