version: '2.1'
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: cinema-nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"

  movies:
    build:
      context: .
      dockerfile: ./movies/Dockerfile
    image: stockallj/cinema-movies
    container_name: cinema-movies
    depends_on:
      - db
      - proxy
    links:
      - db
    environment:
      VIRTUAL_HOST: movies.dev
      DATABASE_HOST: db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://movies.dev/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  bookings:
    build:
      context: .
      dockerfile: ./bookings/Dockerfile
    image: stockallj/cinema-bookings
    container_name: cinema-bookings
    depends_on:
      - db
      - proxy
    links:
      - db
    environment:
      VIRTUAL_HOST: bookings.dev
      DATABASE_HOST: db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://bookings.dev/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  showtimes:
    build:
      context: .
      dockerfile: ./showtimes/Dockerfile
    image: stockallj/cinema-showtimes
    container_name: cinema-showtimes
    depends_on:
      - db
      - proxy
    links:
      - db
    environment:
      VIRTUAL_HOST: showtimes.dev
      DATABASE_HOST: db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://showtimes.dev/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  users:
    build:
      context: .
      dockerfile: ./users/Dockerfile
    image: stockallj/cinema-users
    container_name: cinema-users
    depends_on:
      - db
      - proxy
    links:
      - db
    environment:
      VIRTUAL_HOST: users.dev
      DATABASE_HOST: db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://users.dev/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  backup:
    build: ./backup
    image: stockallj/cinema-backup
    container_name: cinema-backup
    depends_on:
      - db
      - proxy
    links:
      - db
    volumes:
      - ./backup:/backup:rw
    environment:
      VIRTUAL_HOST: backup.dev
      DATABASE_HOST: db

  db:
    image: mongo:3.3
    container_name: cinema-db
    ports:
      - "27017:27017"
    extra_hosts:
     # The backup and restore scripts use as the hostname
    - "db:127.0.0.1"
