apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: cinema
  labels:
    app: database
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: database
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
  namespace: cinema
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: db
          image: mongo:3.3
          ports:
            - containerPort: 27017
          livenessProbe:
            httpGet:
              path: /health
              port: 27017
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: movies
  namespace: cinema
  labels:
    app: movies
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: movies
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: movies
  namespace: cinema
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
        - name: movies
          image: stockallj/cinema-movies
          env:
            - name: DATABASE_HOST
              value: db
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: cinema
  labels:
    app: users
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: users
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: users
  namespace: cinema
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: stockallj/cinema-users
          env:
            - name: DATABASE_HOST
              value: db
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: bookings
  namespace: cinema
  labels:
    app: bookings
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: bookings
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bookings
  namespace: cinema
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bookings
    spec:
      containers:
        - name: bookings
          image: stockallj/cinema-bookings
          env:
            - name: DATABASE_HOST
              value: db
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: showtimes
  namespace: cinema
  labels:
    app: showtimes
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: showtimes
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: showtimes
  namespace: cinema
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: showtimes
    spec:
      containers:
        - name: showtimes
          image: stockallj/cinema-showtimes
          env:
            - name: DATABASE_HOST
              value: db
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backup
  namespace: cinema
  labels:
    app: backup
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: backup
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backup
  namespace: cinema
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backup
    spec:
      containers:
        - name: backup
          image: stockallj/cinema-backup
          env:
            - name: DATABASE_HOST
              value: db
          ports:
            - containerPort: 8080
